### ISSUE TITLE
Improve finding matches

### ISSUE THREAD

**Issue by skrtdev** [meneses-pt/goals.zone#14]
It seems that goals with title like "Squad (1) - 0 Another - ..." (with round brackets instead of square brackets) doesn't get added

**Comment by meneses-pt** [comment]
Currently I'm testing an alternative method were I use Machine Learning to identify matches.
In a near future I'll release an update where the current system and the ML one will run simultaneously to try to ensure that no match is lost.

**Comment by skrtdev** [comment]
Oh ok nice so I can close it. You could also fix it in regex for now. Anyway, thank you

**Comment by meneses-pt** [comment]
Honestly? I'm afraid of touching that Regex and messing up what I already have 🤣

**Comment by skrtdev** [comment]
Oh ok, I can make a pull request if you want, or I can go sleep, you decide

**Comment by meneses-pt** [comment]
Make your pull request, I'll appreciate it. :)

**Comment by skrtdev** [comment]
Ok

**Comment by skrtdev** [comment]
It seems it works now, maybe you have fixed it
