### ISSUE TITLE
Feature Request: Sort by latest

### ISSUE THREAD

**Issue by dhilipb** [meneses-pt/goals.zone#29]
Hi,

Love the site. Can you provide a feature to sort by latest rather than teams?d
Also, what's the time-frequency that it gets updated by?

Thanks

**Comment by meneses-pt** [comment]
Hi there,

It is currently sorted by latest. Can you please send a screenshot of what you are seeing?

Videos are updated every minute (depending on availability), scores are updated every five minutes.
